version: '3.4'

volumes:
  postgres_data:
services:
  fitnessapp:
    build:
      context: .
      dockerfile: ./FitnessApp/Dockerfile
    ports:
      - "32768:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=fitnessdb;Username=postgres;Password=postgres"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitnessdb
    volumes:    
      - postgres_data:/var/lib/postgresql/data


